name: birthday

on:
  schedule:
    - cron: '00 0 * 1 *'
    - cron: '00 0 * 2 *'
    - cron: '00 0 * 3 *'
    - cron: '00 0 * 4 *'
    - cron: '00 0 * 5 *'
    - cron: '00 0 * 6 *'
    - cron: '00 0 * 7 *'
    - cron: '00 0 * 8 *'
    - cron: '00 0 * 9 *'
    - cron: '00 0 * 10 *'
    - cron: '00 0 * 11 *'
    - cron: '00 0 * 12 *'
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run main.py
      run: |
        python main.py
      env:
        MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
